package pers.illiant.yummy.entity;

import java.io.Serializable;
import java.util.Date;

public class Income implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.share
     *
     * @mbg.generated
     */
    private Double share;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.income_date
     *
     * @mbg.generated
     */
    private Date incomeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table income
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.id
     *
     * @return the value of income.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.id
     *
     * @param id the value for income.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.share
     *
     * @return the value of income.share
     *
     * @mbg.generated
     */
    public Double getShare() {
        return share;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.share
     *
     * @param share the value for income.share
     *
     * @mbg.generated
     */
    public void setShare(Double share) {
        this.share = share;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.income_date
     *
     * @return the value of income.income_date
     *
     * @mbg.generated
     */
    public Date getIncomeDate() {
        return incomeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.income_date
     *
     * @param incomeDate the value for income.income_date
     *
     * @mbg.generated
     */
    public void setIncomeDate(Date incomeDate) {
        this.incomeDate = incomeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", share=").append(share);
        sb.append(", incomeDate=").append(incomeDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}