package pers.illiant.yummy.entity;

import java.io.Serializable;

public class OrderProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.restaurant_id
     *
     * @mbg.generated
     */
    private Integer restaurantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.product_quantity
     *
     * @mbg.generated
     */
    private Integer productQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.product_price
     *
     * @mbg.generated
     */
    private Double productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.order_id
     *
     * @return the value of order_product.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.order_id
     *
     * @param orderId the value for order_product.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.product_name
     *
     * @return the value of order_product.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.product_name
     *
     * @param productName the value for order_product.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.restaurant_id
     *
     * @return the value of order_product.restaurant_id
     *
     * @mbg.generated
     */
    public Integer getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.restaurant_id
     *
     * @param restaurantId the value for order_product.restaurant_id
     *
     * @mbg.generated
     */
    public void setRestaurantId(Integer restaurantId) {
        this.restaurantId = restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.product_quantity
     *
     * @return the value of order_product.product_quantity
     *
     * @mbg.generated
     */
    public Integer getProductQuantity() {
        return productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.product_quantity
     *
     * @param productQuantity the value for order_product.product_quantity
     *
     * @mbg.generated
     */
    public void setProductQuantity(Integer productQuantity) {
        this.productQuantity = productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.product_price
     *
     * @return the value of order_product.product_price
     *
     * @mbg.generated
     */
    public Double getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.product_price
     *
     * @param productPrice the value for order_product.product_price
     *
     * @mbg.generated
     */
    public void setProductPrice(Double productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", productName=").append(productName);
        sb.append(", restaurantId=").append(restaurantId);
        sb.append(", productQuantity=").append(productQuantity);
        sb.append(", productPrice=").append(productPrice);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}