package pers.illiant.yummy.entity;

import java.io.Serializable;

public class OrderProduct implements Serializable {

    public OrderProduct() {
    }

    public OrderProduct(Integer orderId, String foodName, String restaurantId, Integer foodQuantity, Double foodPrice, Integer foodId) {
        this.orderId = orderId;
        this.foodName = foodName;
        this.restaurantId = restaurantId;
        this.foodQuantity = foodQuantity;
        this.foodPrice = foodPrice;
        this.foodId = foodId;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.food_name
     *
     * @mbg.generated
     */
    private String foodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.restaurant_id
     *
     * @mbg.generated
     */
    private String restaurantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.food_quantity
     *
     * @mbg.generated
     */
    private Integer foodQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.food_price
     *
     * @mbg.generated
     */
    private Double foodPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.food_id
     *
     * @mbg.generated
     */
    private Integer foodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.order_id
     *
     * @return the value of order_product.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.order_id
     *
     * @param orderId the value for order_product.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.food_name
     *
     * @return the value of order_product.food_name
     *
     * @mbg.generated
     */
    public String getFoodName() {
        return foodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.food_name
     *
     * @param foodName the value for order_product.food_name
     *
     * @mbg.generated
     */
    public void setFoodName(String foodName) {
        this.foodName = foodName == null ? null : foodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.restaurant_id
     *
     * @return the value of order_product.restaurant_id
     *
     * @mbg.generated
     */
    public String getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.restaurant_id
     *
     * @param restaurantId the value for order_product.restaurant_id
     *
     * @mbg.generated
     */
    public void setRestaurantId(String restaurantId) {
        this.restaurantId = restaurantId == null ? null : restaurantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.food_quantity
     *
     * @return the value of order_product.food_quantity
     *
     * @mbg.generated
     */
    public Integer getFoodQuantity() {
        return foodQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.food_quantity
     *
     * @param foodQuantity the value for order_product.food_quantity
     *
     * @mbg.generated
     */
    public void setFoodQuantity(Integer foodQuantity) {
        this.foodQuantity = foodQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.food_price
     *
     * @return the value of order_product.food_price
     *
     * @mbg.generated
     */
    public Double getFoodPrice() {
        return foodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.food_price
     *
     * @param foodPrice the value for order_product.food_price
     *
     * @mbg.generated
     */
    public void setFoodPrice(Double foodPrice) {
        this.foodPrice = foodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.food_id
     *
     * @return the value of order_product.food_id
     *
     * @mbg.generated
     */
    public Integer getFoodId() {
        return foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.food_id
     *
     * @param foodId the value for order_product.food_id
     *
     * @mbg.generated
     */
    public void setFoodId(Integer foodId) {
        this.foodId = foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", foodName=").append(foodName);
        sb.append(", restaurantId=").append(restaurantId);
        sb.append(", foodQuantity=").append(foodQuantity);
        sb.append(", foodPrice=").append(foodPrice);
        sb.append(", foodId=").append(foodId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}