package pers.illiant.yummy.entity;

import java.io.Serializable;

public class Restaurant implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.restaurant_id
     *
     * @mbg.generated
     */
    private String restaurantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.phoneNumber
     *
     * @mbg.generated
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.lng_lat
     *
     * @mbg.generated
     */
    private String lngLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.imgUrl
     *
     * @mbg.generated
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.shopName
     *
     * @mbg.generated
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.password
     *
     * @mbg.generated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table restaurant
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.restaurant_id
     *
     * @return the value of restaurant.restaurant_id
     *
     * @mbg.generated
     */
    public String getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.restaurant_id
     *
     * @param restaurantId the value for restaurant.restaurant_id
     *
     * @mbg.generated
     */
    public void setRestaurantId(String restaurantId) {
        this.restaurantId = restaurantId == null ? null : restaurantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.address
     *
     * @return the value of restaurant.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.address
     *
     * @param address the value for restaurant.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.type
     *
     * @return the value of restaurant.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.type
     *
     * @param type the value for restaurant.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.phoneNumber
     *
     * @return the value of restaurant.phoneNumber
     *
     * @mbg.generated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.phoneNumber
     *
     * @param phoneNumber the value for restaurant.phoneNumber
     *
     * @mbg.generated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.lng_lat
     *
     * @return the value of restaurant.lng_lat
     *
     * @mbg.generated
     */
    public String getLngLat() {
        return lngLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.lng_lat
     *
     * @param lngLat the value for restaurant.lng_lat
     *
     * @mbg.generated
     */
    public void setLngLat(String lngLat) {
        this.lngLat = lngLat == null ? null : lngLat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.imgUrl
     *
     * @return the value of restaurant.imgUrl
     *
     * @mbg.generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.imgUrl
     *
     * @param imgurl the value for restaurant.imgUrl
     *
     * @mbg.generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.shopName
     *
     * @return the value of restaurant.shopName
     *
     * @mbg.generated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.shopName
     *
     * @param shopName the value for restaurant.shopName
     *
     * @mbg.generated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.password
     *
     * @return the value of restaurant.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.password
     *
     * @param password the value for restaurant.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", restaurantId=").append(restaurantId);
        sb.append(", address=").append(address);
        sb.append(", type=").append(type);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", lngLat=").append(lngLat);
        sb.append(", imgurl=").append(imgurl);
        sb.append(", shopName=").append(shopName);
        sb.append(", password=").append(password);
        sb.append(", email=").append(email);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public Restaurant() {
    }

    public Restaurant(String restaurantId, String address, String type, String phoneNumber, String lngLat, String imgurl, String shopName, String password, String email) {
        this.restaurantId = restaurantId;
        this.address = address;
        this.type = type;
        this.phoneNumber = phoneNumber;
        this.lngLat = lngLat;
        this.imgurl = imgurl;
        this.shopName = shopName;
        this.password = password;
        this.email = email;
    }
}