package pers.illiant.yummy.entity;

import java.io.Serializable;
import java.util.Date;

public class UpdateRequest implements Serializable {

    public UpdateRequest() {
    }

    public UpdateRequest(String restaurantId, String shopname, String address, String lngLat, String imgurl, String type, String phonenumber) {
        this.restaurantId = restaurantId;
        this.shopname = shopname;
        this.address = address;
        this.lngLat = lngLat;
        this.imgurl = imgurl;
        this.type = type;
        this.phonenumber = phonenumber;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_request.request_id
     *
     * @mbg.generated
     */
    private Integer requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_request.restaurant_id
     *
     * @mbg.generated
     */
    private String restaurantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_request.shopName
     *
     * @mbg.generated
     */
    private String shopname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_request.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_request.lng_lat
     *
     * @mbg.generated
     */
    private String lngLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_request.imgUrl
     *
     * @mbg.generated
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_request.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_request.phoneNumber
     *
     * @mbg.generated
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_request.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_request.request_time
     *
     * @mbg.generated
     */
    private Date requestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table update_request
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_request.request_id
     *
     * @return the value of update_request.request_id
     *
     * @mbg.generated
     */
    public Integer getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_request.request_id
     *
     * @param requestId the value for update_request.request_id
     *
     * @mbg.generated
     */
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_request.restaurant_id
     *
     * @return the value of update_request.restaurant_id
     *
     * @mbg.generated
     */
    public String getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_request.restaurant_id
     *
     * @param restaurantId the value for update_request.restaurant_id
     *
     * @mbg.generated
     */
    public void setRestaurantId(String restaurantId) {
        this.restaurantId = restaurantId == null ? null : restaurantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_request.shopName
     *
     * @return the value of update_request.shopName
     *
     * @mbg.generated
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_request.shopName
     *
     * @param shopname the value for update_request.shopName
     *
     * @mbg.generated
     */
    public void setShopname(String shopname) {
        this.shopname = shopname == null ? null : shopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_request.address
     *
     * @return the value of update_request.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_request.address
     *
     * @param address the value for update_request.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_request.lng_lat
     *
     * @return the value of update_request.lng_lat
     *
     * @mbg.generated
     */
    public String getLngLat() {
        return lngLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_request.lng_lat
     *
     * @param lngLat the value for update_request.lng_lat
     *
     * @mbg.generated
     */
    public void setLngLat(String lngLat) {
        this.lngLat = lngLat == null ? null : lngLat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_request.imgUrl
     *
     * @return the value of update_request.imgUrl
     *
     * @mbg.generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_request.imgUrl
     *
     * @param imgurl the value for update_request.imgUrl
     *
     * @mbg.generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_request.type
     *
     * @return the value of update_request.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_request.type
     *
     * @param type the value for update_request.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_request.phoneNumber
     *
     * @return the value of update_request.phoneNumber
     *
     * @mbg.generated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_request.phoneNumber
     *
     * @param phonenumber the value for update_request.phoneNumber
     *
     * @mbg.generated
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_request.state
     *
     * @return the value of update_request.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_request.state
     *
     * @param state the value for update_request.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_request.request_time
     *
     * @return the value of update_request.request_time
     *
     * @mbg.generated
     */
    public Date getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_request.request_time
     *
     * @param requestTime the value for update_request.request_time
     *
     * @mbg.generated
     */
    public void setRequestTime(Date requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_request
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", requestId=").append(requestId);
        sb.append(", restaurantId=").append(restaurantId);
        sb.append(", shopname=").append(shopname);
        sb.append(", address=").append(address);
        sb.append(", lngLat=").append(lngLat);
        sb.append(", imgurl=").append(imgurl);
        sb.append(", type=").append(type);
        sb.append(", phonenumber=").append(phonenumber);
        sb.append(", state=").append(state);
        sb.append(", requestTime=").append(requestTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}